apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-clouddriver
  labels:
    app: {{ template "fullname" . }}
    component: clouddriver
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/spinnaker-config.yaml") . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
        component: clouddriver
    spec:
      serviceAccountName: {{ template "fullname" . }}
      containers:
        - image: {{ .Values.images.clouddriver }}
          name: clouddriver
          ports:
            - containerPort: 7002
              name: clouddriver
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: {{ template "fullname" . }}-spinnaker-config
            - mountPath: /tmp/registry
              name: {{ template "fullname" . }}-registry
            - mountPath: /opt/passwords
              name: token-refresh-shared
          readinessProbe:
            httpGet:
              path: /health
              port: 7002
            initialDelaySeconds: 20
            timeoutSeconds: 1
        - image: quay.io/skuid/ecr-token-refresh:latest
          name: ecr-token-refresh
          imagePullPolicy: Always
          volumeMounts:
           - name: token-refresh-config
             mountPath: /opt/config/ecr-token-refresh
           - name: token-refresh-shared
             mountPath: /opt/passwords
      volumes:
        - name: {{ template "fullname" . }}-spinnaker-config
          configMap:
            name: {{ template "fullname" . }}-spinnaker-config
        - name: {{ template "fullname" . }}-registry
          secret:
            secretName: {{ template "fullname" . }}-registry
        - name: token-refresh-shared # shared volume
          emptyDir: {}
        - name: token-refresh-config
          configMap:
            name: {{ template "fullname" . }}-spinnaker-config
